// This file is auto-generated by Blunt. DO NOT EDIT.

declare module '*.ts' {
	import type { BluntGlobalConfig } from './blunt/types';

	export const config: BluntGlobalConfig;

	export default function (): BluntGlobalConfig;
}

declare module 'blunt.config.ts' {
	import type { BluntGlobalConfig } from './blunt/types';

	export default BluntGlobalConfig;
}
